services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: damguard
      POSTGRES_PASSWORD: damguard
      POSTGRES_DB: damguard
    ports:
      - "5432:5432"

  clickhouse:
    image: clickhouse/clickhouse-server:24
    ports:
      - "8123:8123"
      - "9000:9000"

  adminer:
    image: adminer
    ports:
      - "8080:8080"