// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findOrCreateUser = `-- name: FindOrCreateUser :one
INSERT INTO users (email, provider, phone, fullname, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (email)
DO UPDATE SET
    phone = EXCLUDED.phone,
    provider = EXCLUDED.provider,
    updated_at = NOW()
RETURNING id, email, fullname, password_hash, phone, role, provider
`

type FindOrCreateUserParams struct {
	Email        string
	Provider     interface{}
	Phone        sql.NullString
	Fullname     string
	PasswordHash sql.NullString
}

type FindOrCreateUserRow struct {
	ID           uuid.UUID
	Email        string
	Fullname     string
	PasswordHash sql.NullString
	Phone        sql.NullString
	Role         UserRole
	Provider     interface{}
}

func (q *Queries) FindOrCreateUser(ctx context.Context, arg FindOrCreateUserParams) (FindOrCreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, findOrCreateUser,
		arg.Email,
		arg.Provider,
		arg.Phone,
		arg.Fullname,
		arg.PasswordHash,
	)
	var i FindOrCreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fullname,
		&i.PasswordHash,
		&i.Phone,
		&i.Role,
		&i.Provider,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, phone, email, fullname, provider, password_hash, role, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Fullname,
		&i.Provider,
		&i.PasswordHash,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}
